name: Hello World Action

on:
  push:
    branches:
      - master

jobs:
  print-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Print Hello World
        run: echo "Hello, World!"

        
    
          
